upstream users_backend {
    server users1:5000;
    server users2:5000;
}

server {
    listen 80;

    location /api/users/ {
        proxy_pass http://users_backend/;
    }

    location /api/products/ {
        proxy_pass http://products:5000/;
    }
}
